# Generated by Django 2.0.7 on 2019-03-13 06:44

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD_DOMAIN', 'ADD DOMAIN'), ('EDIT_DOMAIN', 'EDIT DOMAIN'), ('DELETE_DOMAIN', 'DELETE DOMAIN'), ('LOGIN', 'LOGIN')], max_length=255)),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=500, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone3', models.CharField(blank=True, max_length=255, null=True)),
                ('date_register', models.DateField(blank=True, null=True)),
                ('date_expire', models.DateField(blank=True, null=True)),
                ('date_last_scan', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pci_scan', models.BooleanField(default=False)),
                ('pci_scan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('TEMPORARY_CLOSED', 'TEMPORARY CLOSED'), ('CLOSED', 'CLOSED')], default='ACTIVE', max_length=255)),
            ],
        ),
    ]
