# Generated by Django 2.0.7 on 2019-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20190313_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='alexa',
            field=models.CharField(choices=[(0, 'OFF'), (1, 'REQUIRES_CONFIRM'), (2, 'ON')], default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='alexa_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='email2',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='email3',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='redirect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
