# Generated by Django 2.0.7 on 2019-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20190314_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='alexa',
            field=models.CharField(choices=[('OFF', 'OFF'), ('REQUIRES_CONFIRM', 'REQUIRES_CONFIRM'), ('ON', 'ON')], default='OFF', max_length=255),
        ),
    ]
