# Generated by Django 2.0.7 on 2018-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20181104_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('TEMPORARY_CLOSED', 'TEMPORARY CLOSED'), ('CLOSED', 'CLOSED')], default='ACTIVE', max_length=255),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('ADD_DOMAIN', 'ADD DOMAIN'), ('EDIT_DOMAIN', 'EDIT DOMAIN'), ('DELETE_DOMAIN', 'DELETE DOMAIN'), ('LOGIN', 'LOGIN')], max_length=255),
        ),
    ]
