# Generated by Django 2.0.7 on 2019-03-17 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0005_alexatraffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainConfirmUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('new_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('ADD_DOMAIN', 'ADD DOMAIN'), ('EDIT_DOMAIN', 'EDIT DOMAIN'), ('DELETE_DOMAIN', 'DELETE DOMAIN'), ('LOGIN', 'LOGIN'), ('ALEXA', 'ALEXA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='alexa',
            field=models.CharField(choices=[('OFF', 'OFF'), ('REQUIRES_ON', 'REQUIRES_ON'), ('ON', 'ON'), ('ALEXA_REQUIRES_OFF', 'ALEXA_REQUIRES_OFF')], default='OFF', max_length=255),
        ),
        migrations.AddField(
            model_name='domainconfirmupdate',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirm_up_set', to='domains.Domain'),
        ),
        migrations.AddField(
            model_name='domainconfirmupdate',
            name='responsible_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainconfirmupdate',
            name='user_changed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_changed', to=settings.AUTH_USER_MODEL),
        ),
    ]
