# Generated by Django 2.0.13 on 2019-03-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20190317_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='alexatraffic',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='domainconfirmupdate',
            options={'ordering': ['-id']},
        ),
    ]
