# Generated by Django 2.0.7 on 2018-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20181211_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='company_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='date_last_scan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='pci_scan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
