# Generated by Django 2.0.13 on 2019-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_auto_20190321_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('REQUIRES_TEMPORARY_CLOSED', 'REQUIRES_TEMPORARY_CLOSED'), ('TEMPORARY_CLOSED', 'TEMPORARY_CLOSED'), ('REQUIRES_CLOSED', 'REQUIRES_CLOSED'), ('CLOSED', 'CLOSED'), ('REQUIRES_ACTIVE', 'REQUIRES_ACTIVE')], default='ACTIVE', max_length=255),
        ),
    ]
