# Generated by Django 2.0.7 on 2018-12-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_auto_20181211_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.Domain'),
        ),
    ]
