# Generated by Django 2.0.7 on 2018-12-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_actionlog_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
