# Generated by Django 2.0.7 on 2019-03-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190313_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='pidgin',
            field=models.BooleanField(default=False),
        ),
    ]
