# Generated by Django 2.0.7 on 2019-03-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190313_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'permissions': (('supermanagers', 'Can get access to advanced functional'), ('can_manage_alexa_traffic', 'Can manage Alexa traffic'))},
        ),
    ]
